### PR TITLE
RUMM-170 Allow Datadog.initialize() to be called more than once

### LINKED ISSUE #86: Prevent Multiple Calls To Initialize
I'm using Roboelectric for android unit tests. This [calls Application#onCreate every test](https://github.com/robolectric/robolectric/issues/3108) and has an unfortunate interaction with this library. It causes `Datadog.initialize` to be called multiple times. So every test in the suite fails.

I have a workaround by manually tracking whether it's initialized. However, it could be helpful to have a method like `Datadog.isInitialized` to tell whether `Datadog.initialize` can be called safely.

Or, a method like `Datadog.setInTestMode`. [SoLoader](https://github.com/facebook/SoLoader) (another library that I had issues with) uses this strategy and has `SoLoader.setInTestMode`. I think the idea with this is you can call it in the test runner instead of modifying the `Application`.

The error:
```
java.lang.IllegalStateException: Datadog has already been initialized.
	at com.datadog.android.Datadog.initialize(Datadog.kt:94)
	at com.datadog.android.Datadog.initialize$default(Datadog.kt:92)
	at com.datadog.android.Datadog.initialize(Datadog.kt)
	at com.aapmobileedb.MainApplication.onCreate(MainApplication.java:62)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$installAndCreateApplication$0(AndroidTestEnvironment.java:276)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:75)
	at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:276)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:169)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:301)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:243)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by xgouchet**
### What does this PR do?

When calling `Datadog.initialize` more than once, all calls after the first one are ignored, and a warning message will be printed to the Logcat to warn the dev.

### Motivation

Resolves #86

### Review checklist (to be filled by reviewers)

- [X] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [X] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [X] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

### CODE REVIEW

File: dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt [hunk 1]
```diff
@@ -92,7 +93,13 @@ object Datadog {
         clientToken: String,
         endpointUrl: String? = null
     ) {
-        check(!initialized) { "Datadog has already been initialized." }
+        if (initialized) {
```
Comment (mariusc83) [inline dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt]: That's cool. Have one question though...if the user will want to use a logger without initialising the SDK this will still crash at runtime right ? Maybe we need to look into this also.

Comment (xgouchet) [reply dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt]: Yes it'll crash. WHy would they import datadog and not initialise it ?

Comment (mariusc83) [reply dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt]: Not sure...just thinking about it...I will ask Daniel to tell us also his opinion.
