### PR TITLE
RUMM-1580: Fix SDK initialization crash on KitKat for a minified build due to DexVerifier rejecting opcode

### LINKED ISSUE #678: KitKat crash when ProGuard is enabled
**Describe what happened**

Crash stack trace: 
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.***, PID: 10436
    java.lang.VerifyError: com/datadog/android/rum/tracking/ActivityViewTrackingStrategy
        at com.datadog.android.core.configuration.Configuration.<clinit>(Configuration.kt:633)
        at com.datadog.android.core.configuration.Configuration$Builder.<init>(Configuration.kt:125)
        at app code
```

The following logs can be observed in LogCat:

```
I/dalvikvm: Could not find method android.app.Application$ActivityLifecycleCallbacks.onActivityPostResumed, referenced from method com.datadog.android.rum.tracking.ActivityViewTrackingStrategy.onActivityPostResumed
W/dalvikvm: VFY: unable to resolve virtual method 257: Landroid/app/Application$ActivityLifecycleCallbacks;.onActivityPostResumed (Landroid/app/Activity;)V
W/dalvikvm: VFY:  rejecting opcode 0x6f at 0x0005
W/dalvikvm: VFY:  rejected Lcom/datadog/android/rum/tracking/ActivityViewTrackingStrategy;.onActivityPostResumed (Landroid/app/Activity;)V
W/dalvikvm: Verifier rejected class Lcom/datadog/android/rum/tracking/ActivityViewTrackingStrategy;
W/dalvikvm: Exception Ljava/lang/VerifyError; thrown while initializing Lcom/datadog/android/core/configuration/Configuration;
D/AndroidRuntime: Shutting down VM
```

**Steps to reproduce the issue:**

Enable ProGuard by setting `isMinifyEnabled` to true in the release build type, run release variant on KitKat, observe crash when DataDog SDK is initialised.

**Describe what you expected:**

No crash.

**Additional context**
 - Android OS version: 4.4 KitKat
 - Device Model: any
 - Datadog SDK version: 1.8.1 and newer
 - Versions of any other relevant dependencies (OkHttp, …): OkHttp 3.12.13
 - Proguard configuration: 
<details>
  <summary>Click to expand</summary>
  
  ```
-dontobfuscate

-keepattributes SourceFile,LineNumberTable

-dontnote com.google.android.gms.maps.internal.zzy

-keepclassmembers,includedescriptorclasses public class * extends android.view.View {
   void set*(***);
   *** get*();
}

-dontwarn org.apache.commons.compress.archivers.sevenz.**
-dontwarn org.apache.commons.compress.compressors.lzma.**
-dontnote org.apache.commons.compress.compressors.lzma.**
-dontwarn org.apache.commons.compress.compressors.xz.**
-dontnote org.apache.commons.compress.compressors.xz.**

-dontwarn org.joda.time.**

-keep class org.joda.time.tz.Provider
-keep class org.joda.time.tz.NameProvider

-dontnote com.daimajia.swipe.SwipeLayout

-dontnote com.koushikdutta.async.http.SSLEngineSNIConfigurator$EngineHolder
-dontnote com.koushikdutta.async.http.spdy.SpdyMiddleware

-dontnote okhttp3.internal.platform.Platform
-dontnote okhttp3.internal.platform.AndroidPlatform
-dontnote okhttp3.internal.platform.AndroidPlatform$CloseGuard

-dontwarn java.nio.file.**
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement

-dontnote android.net.http.**
-dontnote org.apache.http.**

-dontnote sun.misc.Unsafe

-dontnote com.google.android.gms.security.ProviderInstaller

-dontnote kotlin.internal.**
-dontnote kotlin.reflect.jvm.internal.**

-dontwarn javax.lang.model.**
-dontwarn com.squareup.javapoet.**
-dontwarn com.squareup.moshi.**
-dontwarn org.jetbrains.annotations.**

-dontnote androidx.work.impl.**
-dontwarn sun.misc.Unsafe
-dontwarn android.app.job.JobParameters
-keep class androidx.work.WorkerParameters
-dontnote androidx.work.WorkParameters

-keepclassmembers class * extends androidx.work.Worker {
    <init>(...);
}

-keep class kotlin.coroutines.CoroutineContext*
-keep class kotlin.jvm.internal.DefaultConstructorMarker
-keep class kotlin.jvm.functions.Function2
-keep class androidx.lifecycle.**
-dontwarn kotlinx.atomicfu.AtomicBoolean
-keep class kotlinx.coroutines.android.AndroidExceptionPreHandler
-keep class kotlinx.coroutines.android.AndroidDispatcherFactory

-dontwarn org.slf4j.**

-keepattributes Signature,InnerClasses,EnclosingMethod

-dontwarn androidx.work.impl.background.firebase.*
-dontwarn kotlinx.atomicfu.*

-keep class * implements com.apollographql.apollo.api.InputType { *; }

-keepnames class * implements com.apollographql.apollo.api.internal.ResponseFieldMapper

  ```
  
</details>

 - Gradle Plugins: Android Gradle Plugin 7.0

### PR DESCRIPTION
**Pull request by 0xnm**
### What does this PR do?

Fixes #678. Crash happens only on KitKat with minified build due to `DexVerfier` rejecting bytecode of the class `ActivityViewTrackingStrategy`, specifically bytecode of this line https://github.com/DataDog/dd-sdk-android/blob/34933826d3b36988dee8e9fa8a76b829b4a70314/dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/ActivityViewTrackingStrategy.kt#L72

Error says:

```
I/dalvikvm: Could not find method android.app.Application$ActivityLifecycleCallbacks.onActivityPostResumed, referenced from method com.datadog.android.rum.tracking.ActivityViewTrackingStrategy.onActivityPostResumed
W/dalvikvm: VFY: unable to resolve virtual method 257: Landroid/app/Application$ActivityLifecycleCallbacks;.onActivityPostResumed (Landroid/app/Activity;)V
W/dalvikvm: VFY:  rejecting opcode 0x6f at 0x0005
W/dalvikvm: VFY:  rejected Lcom/datadog/android/rum/tracking/ActivityViewTrackingStrategy;.onActivityPostResumed (Landroid/app/Activity;)V
W/dalvikvm: Verifier rejected class Lcom/datadog/android/rum/tracking/ActivityViewTrackingStrategy;
```

Opcode `0x6f` corresponds to the [super](https://android.googlesource.com/platform/dalvik/+/android-4.4.2_r2/libdex/DexOpcodes.h#182) invocation. There is nothing special about this opcode, I can see other instances of this opcode being successfully replaced instead of being rejected. And this error happens only on KitKat (hence Dalvik), it doesn't repro with newer APIs (ART).

Not sure why it happens, probably there is something special about backporting `default` (`onActivityPostResumed` is a `default` method) methods to the pre-Lollipop APIs, but the easiest fix is just to remove `super` call and it is safe to do with current inheritance hierarchy because default implementation [is just empty](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/app/Application.java;l=126;drc=5d123b67756dffcfdebdb936ab2de2b29c799321).

Things like using `RequiresApi`, `TargetApi`, wrapping in build version check condition didn't help. Adding ProGuard instructions also didn't help: APK explorer shows that the necessary class and method are there, but app still crashes.

### Review checklist (to be filled by reviewers)

- [x] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [x] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [x] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

### CODE REVIEW

File: dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/ActivityViewTrackingStrategy.kt [hunk 1]
```diff
@@ -69,7 +69,9 @@ class ActivityViewTrackingStrategy @JvmOverloads constructor(
     }
 
     override fun onActivityPostResumed(activity: Activity) {
-        super.onActivityPostResumed(activity)
+        // this method doesn't call super, because having super call creates a crash
```
Comment (xgouchet) [inline dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/ActivityViewTrackingStrategy.kt:72]: Wouldn't that break the behavior on recent version of the OS ? Instead maybe we could have an 
 ```
if (Version > KitKat) {
    super.onActivityPostResumed(activity)
    // …
}
```

**Review by xgouchet — CHANGES_REQUESTED** [review]

File: dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/ActivityViewTrackingStrategy.kt (hunk 1 above)
Comment (0xnm) [reply dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/ActivityViewTrackingStrategy.kt:72]: it won't break, since `onActivityPostResumed` in `super` is empty. Version check doesn't help as I've stated in the PR description.

**Review by xgouchet — APPROVED** [review]

File: dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/ActivityViewTrackingStrategy.kt (hunk 1 above)
Comment (0xnm) [reply dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/ActivityViewTrackingStrategy.kt:72]: Yes, forward compatibility can be a concern. I'm not sure if `ActivityViewTrackingStrategyKitKat` would work though, because it means that both `ActivityViewTrackingStrategyKitKat` and `ActivityViewTrackingStrategyLollipop` will be referenced from the same class in the `import` statement, and it means `DexVerifier` will still go through the class with `super` call during class load process.
