### PR TITLE
RUM-971: Report ApplicationLaunch view even if first RUM event is not interaction

### LINKED ISSUE #1523: App startup time missing when using version 1.19.2
**Describe what happened**
We upgraded to SDK version 1.19.2 and I noticed that the startup time metric is now gone for any app versions that use this SDK version. When I downgrade the SDK locally to 1.19.1, I can get it back.

**Steps to reproduce the issue:**
Use SDK version 1.19.2 and notice that the app startup time is empty on the DD dashboard.

Screenshot 2023-07-05 at 13 04 13

**Describe what you expected:**
I expect the startup time to be tracked.

**Additional context**
 - Android OS version:
 - Device Model:
 - Datadog SDK version: 1.19.2
 - Versions of any other relevant dependencies (OkHttp, …): 
 - Proguard configuration: 
 - Gradle Plugins:

### LINKED ISSUE #1582: application_start action event won't be called when AddLongTask event triggered as a first RUM event
**Describe what happened**

Usually Datadog will trigger `application_start` action event at first.
But when `AddLongTask` event was triggered as a first RUM event, `application_start` action event won't be triggered.

**Steps to reproduce the issue:**

Trigger any `AddLongTask` quickly when just Datadog initialized.

Sample: https://github.com/ken-kentan/dd-sdk-android/pull/2

**Describe what you expected:**

`application_start` action event should be triggered even if the first RUM event was `AddLongTask`.

I investigated around `RumSessionScope` and found than when `AddLongTask` event was triggered as a first event, `sessionState` was changed to `State.EXPIRED`, then `RumSessionScope::handleEvent` passed `noOpWriter` as an `actualWriter` for `ApplicationStarted` event.
I guess `sessionState` shouldn't be `State.EXPIRED` in this case.

**Additional context**
 - Android OS version: N/A
 - Device Model: N/A
 - Datadog SDK version: 1.19.0-2.0.0
 - Versions of any other relevant dependencies (OkHttp, …):  N/A
 - Proguard configuration: N/A
 - Gradle Plugins: N/A

Note: This issue might be same with https://github.com/DataDog/dd-sdk-android/issues/1523

### PR DESCRIPTION
**Pull request by 0xnm**
### What does this PR do?

Fixes #1582 and maybe fixes #1523.

This PR fixes the issue when `ApplicationLaunch` is not reported in case if first RUM event coming is not interaction event. In this case session is not yet active, so we create `ApplicationLaunch` and `ApplicationStarted` action for nothing - they won't be written, because writer is no-op.

This PR moves the logic of creating `ApplicationStarted` event up to the application scope, which makes sense - we have to report it only once in the application lifecycle. Also session we be activated once `ApplicationStarted` event is received by the session scope, meaning that session is created not only by start view or start action events (which makes sense, because we introduced `ApplicationLaunch` view to be independent from background tracking feature).

There is one leftover which I don't personally enjoy - having `applicationDisplayed` property in the scopes (I think this property is vague), but getting rid of it is tricky.

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

### CODE REVIEW

**Review by xgouchet — DISMISSED** [review]
Nice work

File: features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScope.kt [hunk 1]
```diff
@@ -155,6 +169,34 @@ internal class RumApplicationScope(
         }
     }
 
+    @WorkerThread
+    private fun sendApplicationStartEvent(eventTime: Time, writer: DataWriter<Any>) {
+        val processImportance = DdRumContentProvider.processImportance
+        val isForegroundProcess = processImportance ==
+            ActivityManager.RunningAppProcessInfo.IMPORTANCE_FOREGROUND
+        if (isForegroundProcess) {
+            val processStartTime = appStartTimeProvider.appStartTimeNs
```
Comment (jonathanmos) [inline features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScope.kt:178]: minor: since the processStartTime is in ns, should we not rename to processStartTimeNs?

**Review by jonathanmos — DISMISSED** [review]

**Review by mariusc83 — DISMISSED** [review]
