### PR TITLE
RUMM-1048: Fix wrong logcat tag for Timber integration

### LINKED ISSUE #483: Log class names with the Timber logger
When using the Timber logger via
` Timber.plant(new DatadogTree(logger));`
the classname doesn't propagate in the logs.  All logs are tagged with `/DatadogTree: ...... 	| at .log(DatadogTree.kt:32)` instead of the actual tag(class).

If I use the DataDog logger directly it works.  It also works if I plant the Timber.DebugTree with `Timber.plant(new Timber.DebugTree());`

This is happening on 1.7.1 (and prior).

### PR DESCRIPTION
**Pull request by 0xnm**
### What does this PR do?

This PR fixes wrong tag in the logcat output for Timber integration, when wrong call stack element was picked (closes #483)

### Motivation

Existing issue #483

### Additional Notes

This is not a universal solution and will fix only Timber integration case. Need to come up with better call site matching later.

### Review checklist (to be filled by reviewers)

- [x] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [x] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [x] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

### CODE REVIEW

File: dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandler.kt [hunk 1]
```diff
@@ -70,14 +70,22 @@ internal class LogcatLogHandler(
...
             null
         }
     }
 
+    internal fun findValidCallStackElement(
+        stackTrace: Array<StackTraceElement>
+    ): StackTraceElement? {
+        return stackTrace.firstOrNull {
+            it.className !in ignoredClassNames &&
+                !it.className.startsWith("com.datadog.android.timber") &&
```
Comment (0xnm) [inline dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandler.kt:84]: `startsWith` instead of `contains` to be more restrictive, since the latter can lead to false positives.

File: dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandlerTest.kt [hunk 2]
```diff
@@ -84,4 +84,52 @@ internal class LogcatLogHandlerTest {
                     "\$runnable\$1"
             )
     }
+
+    @Test
+    fun `resolves valid stack trace element when wrapped in timber`() {
+
+        // Given
+        val rawStackTrace =
```
Comment (0xnm) [inline dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandlerTest.kt:92]: since I'm creating fake stack trace which is not bound to the real runtime execution, it seems there is no need to create a similar test in the `javaTest` folder. please let me know if I'm wrong.

Comment (xgouchet) [reply dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandlerTest.kt:92]: Indeed that sounds unnecessary

Comment (mariusc83) [reply dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandlerTest.kt:93]: I understood that @xgouchet will introduce you later to Elmyr :). Having this in mind you could re - write this test to introduce more randomness as :
```
    @Test
    fun `resolves valid stack trace element when wrapped in timber`(forge: Forge) {

        // Given
        val ignoredClassNamesRegEx = LogcatLogHandler.ignoredClassNames.joinToString("|")
            .replace(".", "\\.")
        val expectedElementIndex = forge.anInt(min=2,max = 10)
        val stackTrace = Array<StackTraceElement>(
            expectedElementIndex +
                forge.anInt(min=1,max = 10)
        ) {
            if (it < expectedElementIndex / 2) {
                StackTraceElement(
                    forge.aStringMatching("((com\\.datadog\\.android)|(timber\\.log))(.+)"),
                    forge.anAlphabeticalString(),
                    forge.anAlphabeticalString(),
                    it
                )
            } else if (it < expectedElementIndex) {
                StackTraceElement(
                    forge.aStringMatching("($ignoredClassNamesRegEx)"),
                    forge.anAlphabeticalString(),
                    forge.anAlphabeticalString(),
                    it
                )
            } else {
                StackTraceElement(
                    forge.aStringMatching("[^ctCT](.+)($ignoredClassNamesRegEx)[a]"),
                    forge.anAlphabeticalString(),
                    forge.anAlphabeticalString(),
                    it
                )
            }
        }

        // When
        val element = testedHandler.findValidCallStackElement(stackTrace)

        // Then
        checkNotNull(element)
        assertThat(element)
            .isEqualTo(stackTrace[expectedElementIndex])
    }
```

File: dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandler.kt (hunk 1 above)
Comment (mariusc83) [inline dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandler.kt:84]: is there any particular reason we want to exclude only `com.datadog.android.timber` packages and not the whole `com.datadog.android` package ?

**Review by mariusc83 — CHANGES_REQUESTED** [review]

File: dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandler.kt (hunk 1 above)
Comment (0xnm) [reply dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandler.kt:84]: yes, having only `com.datadog.android` will break logging from the sample app.

Comment (mariusc83) [reply dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandler.kt:84]: Ah...I see now. Maybe is better/safer this way. In this case in the alternative code I proposed above you can use `com//.datadog//.android//.timber` when generating those names or even better extract those package names in `internal static const` values and share the with the test class.

File: dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandler.kt [hunk 3]
```diff
@@ -70,22 +70,30 @@ internal class LogcatLogHandler(
...
+    ): StackTraceElement? {
+        return stackTrace.firstOrNull { element ->
+            element.className !in IGNORED_CLASS_NAMES &&
+                IGNORED_PACKAGE_PREFIXES.none { element.className.startsWith(it) }
+        }
+    }
+
     // endregion
 
     companion object {
```
Comment (0xnm) [inline dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandler.kt:90]: is there any reason `companion` is public? there is no usage of this object in the code anyway.

on another side making it `internal` doesn't help, because `internal` symbols are visible from java side and the only solution to hide it is to either use `JvmName` with java-prohibited style or use `JvmSynthetic`, which is not yet used in the project.

File: dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandlerTest.kt [hunk 4]
```diff
@@ -84,4 +86,57 @@ internal class LogcatLogHandlerTest {
...
+    fun `resolves valid stack trace element when wrapped in timber`(forge: Forge) {
+
+        // Given
+        val forgeFileName: Forge.() -> String = {
+            "${this.anAlphabeticalString(Case.ANY)}.${this.aStringMatching("(kt|java)")}"
+        }
+
+        val ignoredElements = forge.aList {
+
+            val className = if (aBool()) {
```
Comment (0xnm) [inline dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandlerTest.kt:100]: class name and method name formats may not cover all the possible naming variants per JLS (where almost everything is allowed), so it covers only a simple naming scheme. let me know if I should widen name generation.

File: dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandler.kt (hunk 3 above)
Comment (mariusc83) [reply dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandler.kt:90]: nope, there's no special reason for that.

File: dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandlerTest.kt [hunk 5]
```diff
@@ -84,4 +86,57 @@ internal class LogcatLogHandlerTest {
                     "\$runnable\$1"
             )
     }
+
+    @Test
+    fun `resolves valid stack trace element when wrapped in timber`(forge: Forge) {
+
+        // Given
+        val forgeFileName: Forge.() -> String = {
+            "${this.anAlphabeticalString(Case.ANY)}.${this.aStringMatching("(kt|java)")}"
```
Comment (mariusc83) [inline dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandlerTest.kt:95]: you should escape the "."

File: dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandlerTest.kt (hunk 4 above)
Comment (mariusc83) [reply dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandlerTest.kt:100]: I think for me this unit test is enough for now.

File: dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandlerTest.kt [hunk 6]
```diff
@@ -84,4 +86,57 @@ internal class LogcatLogHandlerTest {
...
+                className,
+                anAlphabeticalString(Case.ANY),
+                forgeFileName(this),
+                aSmallInt()
+            )
+        }
+
+        val validElements = forge.aList {
+
+            val className = "com.${anAlphabeticalString(Case.LOWER, 5)}" +
```
Comment (mariusc83) [inline dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandlerTest.kt:119]: Is there any chance that some of these packages can collide with the ignored ones ?

**Review by mariusc83 — APPROVED** [review]

File: dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandlerTest.kt (hunk 5 above)
Comment (0xnm) [reply dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandlerTest.kt:95]: why? it is not a regex pattern

File: dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandlerTest.kt (hunk 6 above)
Comment (0xnm) [reply dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandlerTest.kt:119]: no, there is no such entry matching `com.{5 chars}.{6 chars}.{7 chars}.{8 chars}`. It can be introduced at some point in future, but the probability of that is very low I guess. I just didn't want to introduce something more complex for that generation.

File: dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandlerTest.kt (hunk 5 above)
Comment (mariusc83) [reply dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandlerTest.kt:95]: hmm...maybe I don't interpret it correctly but if you want to have a "." in there you should add it as `\\.` otherwise it will be interpret as the special character `.` which means any character.

Comment (0xnm) [reply dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandlerTest.kt:95]: this is just a plain string literal and not regex pattern, so no need to escape it here. I'm just using lambda with `Forge` receiver.

**Review by xgouchet — APPROVED** [review]
Good work :)
