### PR TITLE
RUMM-2931 prevent reporting ANR when app is in background

### LINKED ISSUE #1067: ANR reports number is significantly different from the Google Play
**Describe what happened**
The number of ANR reports in RUM is significantly more than at Google Play. However, the number of crashes is similar.

**Steps to reproduce the issue:**
1. Integrate DataDog Android SDK
2. Check the RUM error section

**Describe what you expected:**
1. Number of ANR is similar to Google Play's one

P.S. I was not able to find the algorithm of the ANR collection in the documentation.

### PR DESCRIPTION
**Pull request by xgouchet**
### What does this PR do?

Fixes #1067 

This PR prevents reporting false positive ANRs when the application is in background. 

### Motivation

In some cases (#1067) the host application is in background and the SDK detekts multiple SDKs that are not actually perceived by the end user.

### CODE REVIEW

**Review by 0xnm — APPROVED** [review]

**Review by mariusc83 — APPROVED** [review]

File: dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScopeTest.kt [hunk 1]
```diff
@@ -355,6 +358,26 @@ internal class RumViewManagerScopeTest {
         assertThat(testedScope.childrenScopes).hasSize(0)
     }
 
+    @Test
+    fun `𝕄 not start a bg ViewScope 𝕎 handleEvent { app displayed, event is background ANR}`() {
+        // Given
+        testedScope.applicationDisplayed = true
+        val fakeEvent = RumRawEvent.AddError(
+            message = ANRDetectorRunnable.ANR_MESSAGE,
```
Comment (emartynov) [inline dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScopeTest.kt:366]: Probably off topic - from names `ANRDetectorRunnable.ANR_MESSAGE` and `ANRException` I can not drive understanding it is a background ANR.

Comment (emartynov) [reply dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScopeTest.kt:366]: Also, testedScope has `applicationDisplayed` as `true`, which sounds to me as if it is not in the background.
