### PR TITLE
RUM-6104 ensure UploadWorker uses the sdk instance name

### LINKED ISSUE #2252: How can i populate DATADOG_INSTANCE_NAME in UploadWorker.kt?
### Question

When using datadog in a library, i initilize it with an instance name but the name does not get populated into `DATADOG_INSTANCE_NAME` in the `UploadWorker.kt`, this results in an exception thrown inside the worker:

```
SDK instance with name _dd.sdk_core.default is not found, returning no-op implementation. 
Please make sure to call Datadog.initialize([instanceName]) before getting the instance.
SDK instance was requested from: (Ask Gemini)

at com.datadog.android.Datadog.getInstance(Datadog.kt:139)
at com.datadog.android.core.internal.data.upload.UploadWorker.doWork(UploadWorker.kt:42)
at androidx.work.Worker$1.run(Worker.java:82)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
at java.lang.Thread.run(Thread.java:1012)
2024-09-09 11:32:40.574 19812-20100 Datadog 
co.onestep.android.demoapp
E  Datadog has not been initialized.
```

Since those lines
```
 val instanceName = inputData.getString(DATADOG_INSTANCE_NAME)
 val sdkCore = Datadog.getInstance(instanceName) as? InternalSdkCore
```

return a null instance name and the call to Datadog.getInstance(instanceName/*this is always null/*) throws an exception

### PR DESCRIPTION
**Pull request by xgouchet**
### What does this PR do?

When the UploadWorker is woken by the system, it reads the SDK Instance name from the WorkRequest input data, and tries to get the instance with that name. 

However, the instance name was never sent meaning that for applications specifying an instance name would never find a relevant SDK. 

### Motivation

Fixes #2252

### CODE REVIEW

File: dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/DatadogCoreTest.kt [hunk 1]
```diff
@@ -803,6 +805,20 @@ internal class DatadogCoreTest {
         assertThat(testedCore.isDeveloperModeEnabled).isFalse()
     }
 
+    @RepeatedTest(128)
```
Comment (0xnm) [inline dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/DatadogCoreTest.kt:808]: Shouldn't it be just `@Test` here? Is it needed to repeat it so many times?

**Review by 0xnm — APPROVED** [review]

**Comment by ambushwork** [comment]
Question: in the description of the PR it says before the fix, ".. meaning that for applications specifying an instance name would never find a relevant SDK." I wonder how `UploadWorker` can work correctly after a while of application running?

File: dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/DatadogCoreTest.kt (hunk 1 above)
Comment (xgouchet) [reply dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/DatadogCoreTest.kt:808]: You're right, i used it locally :D

**Review by ambushwork — APPROVED** [review]

**Review by mariusc83 — APPROVED** [review]
