### PR TITLE
RUMM-3051: Remove okhttp3.internal package usage

### LINKED ISSUE #1282: Use of an internal okHttp package causes issues/crashes when using a more recent version of okHttp(4+).
https://github.com/DataDog/dd-sdk-android/blob/dde54aa25954bcdcaffb45b89a84d1ee5450e7ff/dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/RequestUniqueIdentifier.kt#L10

According to their own docs this is a little bit [naughty](https://square.github.io/okhttp/changelogs/upgrading_to_okhttp_4/#internal-api-changes)

### PR DESCRIPTION
**Pull request by 0xnm**
### What does this PR do?

Fixes #1282. This PR removes `okhttp3.internal` package usage, we were using `okhttp3.internal.Util.EMPTY_REQUEST`.

There is a [warning](https://square.github.io/okhttp/changelogs/upgrading_to_okhttp_4/#internal-api-changes) about `okhttp3.internal` package usage for OkHttp 4.x, but with OkHttp 4.x this usage didn't cause any problems - the class and field were still there.

However, it seems things are finally moved for OkHttp 5.x (which is in alpha for now, changelog is [here](https://square.github.io/okhttp/changelogs/changelog/)), so to be on the safe side we are getting rid of reference to `okhttp3.internal`.

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

### CODE REVIEW

File: dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/RequestUniqueIdentifier.kt [hunk 1]
```diff
@@ -16,11 +16,25 @@ internal fun identifyRequest(request: Request): String {
...
     } else {
-        val contentLength = body.contentLength()
+        val contentLength = try {
+            body.contentLength()
+        } catch (@Suppress("SwallowedException") ioe: IOException) {
+            0
+        }
         val contentType = body.contentType()
-        "$method•$url•$contentLength•$contentType"
+        // TODO RUMM-3062 It is possible that if requests are say GZIPed (as an example, or maybe
```
Comment (mariusc83) [inline dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/RequestUniqueIdentifier.kt:28]: I thin you are missing something after `as an example` ?

File: dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/RequestUniqueIdentifier.kt [hunk 2]
```diff
@@ -16,11 +16,25 @@ internal fun identifyRequest(request: Request): String {
...
+        //  streaming case?), they all will have contentLength = -1, so if they target the same URL
+        //  they are going to have same identifier, messing up reporting.
+        //  -1 is valid return value for contentLength() call according to the docs and stands
+        //  for "unknown" case.
+        //  We need to have a more precise identification.
+        if (contentType != null || contentLength != 0L) {
```
Comment (mariusc83) [inline dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/RequestUniqueIdentifier.kt:34]: Aren't we worried that we will have too many collisions if we follow what you stated above ? I guess there are many apps there with GZIPed requests.

Comment (0xnm) [reply dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/RequestUniqueIdentifier.kt:34]: No, this is the same behavior what we have right now (because `EMPTY_REQUEST` replace was the body with `contentType == null` and `contentLength == 0`), so we don't introduce any changes to the current behavior.

And later we can improve, this issue exists today as well.

File: dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/RequestUniqueIdentifier.kt (hunk 1 above)
Comment (0xnm) [reply dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/RequestUniqueIdentifier.kt]: GZIP is an example :) I put the bracket at the wrong place, will update it.

**Review by mariusc83 — APPROVED** [review]

**Review by xgouchet — APPROVED** [review]
