### PR TITLE
RUM-673: Log Timber tag

### LINKED ISSUE #2195: TImber Tags are Ignored
### Describe the bug

The `tag` parameters is ignored inside `DatadogTree.log` merthod

### Reproduction steps

```kotlin
Timber
	.tag("tag")
	.w("message")
```

### Logcat logs

message

### Expected behavior

tag message

### Affected SDK versions

2.12.1

### Latest working SDK version

No

### Did you confirm if the latest SDK version fixes the bug?

Yes

### Kotlin / Java version

Kotlin

### Gradle / AGP version

_No response_

### Other dependencies versions

_No response_

### Device Information

_No response_

### Other relevant information

Bug line https://github.com/DataDog/dd-sdk-android/blob/2529684896c167117a3c0e230f51fdcb43059ea2/integrations/dd-sdk-android-timber/src/main/kotlin/com/datadog/android/timber/DatadogTree.kt#L51 - notice lack of `tag` argument

### PR DESCRIPTION
**Pull request by 0xnm**
### What does this PR do?

Resolves #2195. If Timber tag is present, it will be logged as `timber.tag` attribute.

image

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

### CODE REVIEW

File: integrations/dd-sdk-android-timber/src/main/kotlin/com/datadog/android/timber/DatadogTree.kt [hunk 1]
```diff
@@ -48,6 +48,11 @@ class DatadogTree(
         message: String,
         t: Throwable?
     ) {
-        logger.log(priority, message, t)
+        val attributes = if (tag != null) {
+            mapOf("timber.tag" to tag)
```
Comment (mariusc83) [inline integrations/dd-sdk-android-timber/src/main/kotlin/com/datadog/android/timber/DatadogTree.kt:52]: let's extract this in a const `TIMBER_TAG`

**Review by mariusc83 — APPROVED** [review]
