### PR TITLE
RUM-790 Fix PendingTrace ConcurrentModificationException

### LINKED ISSUE #1570: ConcurrentModificationException in TracingInterceptor
Thanks for taking the time for reporting an issue!

**Describe what happened**

```
Fatal Exception: java.util.ConcurrentModificationException:
       at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:970)
       at java.util.LinkedList$ListItr.next(LinkedList.java:892)
       at com.datadog.opentracing.PendingTrace.expireReference(PendingTrace.java:192)
       at com.datadog.opentracing.PendingTrace.expireSpan(PendingTrace.java:118)
       at com.datadog.opentracing.PendingTrace.addSpan(PendingTrace.java:144)
       at com.datadog.opentracing.DDSpan.finishAndAddToTrace(DDSpan.java:101)
       at com.datadog.opentracing.DDSpan.finish(DDSpan.java:110)
       at com.datadog.android.tracing.TracingInterceptor.handleResponse(TracingInterceptor.kt:514)
       at com.datadog.android.tracing.TracingInterceptor.interceptAndTrace(TracingInterceptor.kt:248)
       at com.datadog.android.tracing.TracingInterceptor.intercept(TracingInterceptor.kt:180)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at com.ourpackage.DatadogSpanInterceptor.intercept(DatadogSpanInterceptor.kt:30)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
```

**Steps to reproduce the issue:**
Not sure how to reproduce it but we've had a few reports of this exception.
**Describe what you expected:**

**Additional context**
 - Android OS version: So far in Android 12 & 13
 - Device Model: Galaxy Z Fold4, Model:Galaxy S21+ 5G, Redmi Note 12, Model:Camon 17, ...
 - Datadog SDK version: 1.19.2
 - Versions of any other relevant dependencies (OkHttp, …): OkHttp=4.11.0
 - Proguard configuration: 
 - Gradle Plugins:

### PR DESCRIPTION
**Pull request by xgouchet**
### What does this PR do?

Add some thread safe guards for PendingTrace, and prevent `ConcurrentModificationException`.

### Additional Notes

Fixes #1570 

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

### CODE REVIEW

File: features/dd-sdk-android-trace/src/main/java/com/datadog/opentracing/PendingTrace.java [hunk 1]
```diff
@@ -178,25 +180,27 @@ public void cancelContinuation(final ContinuableScope.Continuation continuation)
...
-                partialTrace.add(span);
-                completedSpanCount.decrementAndGet();
-                it.remove();
+    synchronized(this) {
+      final int count = pendingReferenceCount.decrementAndGet();
+      if (count == 0) {
+        write();
+      } else {
+        if (tracer.getPartialFlushMinSpans() > 0 && size() > tracer.getPartialFlushMinSpans()) {
+          synchronized (this) {
```
Comment (0xnm) [inline features/dd-sdk-android-trace/src/main/java/com/datadog/opentracing/PendingTrace.java:189]: we probably don't need this one, because we are already in `synchronized` block. But we may want to keep it although to simplify viewing the diff with `dd-trace-java`.

File: features/dd-sdk-android-trace/src/test/kotlin/com/datadog/opentracing/PendingTraceTest.kt [hunk 2]
```diff
@@ -0,0 +1,112 @@
...
+
+    @Mock
+    lateinit var mockTracer: DDTracer
+
+    lateinit var fakeTraceId: BigInteger
+
+    @Test
+    fun `PendingTrace is thread safe`(forge: Forge) {
+        whenever(mockTracer.partialFlushMinSpans) doReturn 1
+        fakeTraceId = BigInteger.valueOf(forge.aLong())
```
Comment (0xnm) [inline features/dd-sdk-android-trace/src/test/kotlin/com/datadog/opentracing/PendingTraceTest.kt:45]: seems it can be a local variable instead of the property

File: features/dd-sdk-android-trace/src/test/kotlin/com/datadog/opentracing/PendingTraceTest.kt [hunk 3]
```diff
@@ -0,0 +1,112 @@
...
+        val pendingTrace = PendingTrace(mockTracer, fakeTraceId)
+        val rootSpan = forge.fakeSpan(pendingTrace, mockTracer, fakeTraceId, BigInteger.ZERO)
+        val countDownLatch = CountDownLatch(2)
```
Comment (0xnm) [inline features/dd-sdk-android-trace/src/test/kotlin/com/datadog/opentracing/PendingTraceTest.kt:48]: why do we have 2 for the latch, but starting 4 threads which are decrementing the latch? shouldn't the numbers be the same

File: features/dd-sdk-android-trace/src/test/kotlin/com/datadog/opentracing/PendingTraceTest.kt [hunk 4]
```diff
@@ -0,0 +1,112 @@
...
+
+        val runnables = Array(4) {
+            StressTestRunnable(pendingTrace, mockTracer, rootSpan, forge, countDownLatch)
+        }
+        runnables.forEach { Thread(it).start() }
+
+        countDownLatch.await(10, TimeUnit.SECONDS)
```
Comment (0xnm) [inline features/dd-sdk-android-trace/src/test/kotlin/com/datadog/opentracing/PendingTraceTest.kt:55]: this may make test flaky, shouldn't we just use simple `await` knowing that all runnables will complete anyway?

File: features/dd-sdk-android-trace/src/main/java/com/datadog/opentracing/PendingTrace.java [hunk 5]
```diff
@@ -178,25 +180,27 @@ public void cancelContinuation(final ContinuableScope.Continuation continuation)
...
-            final DDSpan rootSpan = getRootSpan();
-            final List<DDSpan> partialTrace = new ArrayList(size());
-            final Iterator<DDSpan> it = iterator();
-            while (it.hasNext()) {
-              final DDSpan span = it.next();
-              if (span != rootSpan) {
-                partialTrace.add(span);
-                completedSpanCount.decrementAndGet();
-                it.remove();
+    synchronized(this) {
```
Comment (0xnm) [inline features/dd-sdk-android-trace/src/main/java/com/datadog/opentracing/PendingTrace.java:183]: do we need this one? it seems that code between L184 and L186 should _probably_ be safe without it (it is using atomic primitives and references other classes only). And code below L189 already has `synchronized` block. Do we have a test failure without that change?

File: features/dd-sdk-android-trace/src/test/kotlin/com/datadog/opentracing/PendingTraceTest.kt (hunk 4 above)
Comment (xgouchet) [reply features/dd-sdk-android-trace/src/test/kotlin/com/datadog/opentracing/PendingTraceTest.kt:55]: > all runnables will complete anyway?
Actually that's not true: if an exception happens in the Runnable other than `ConcurrentModificationException`, then the thread will crash without crashing the test run, and the `countDownLatch` won't be decreased. 
I timed the tests as taking 1.5 seconds, so 10 seconds gives a lot of margin to prevent flakiness.

File: features/dd-sdk-android-trace/src/main/java/com/datadog/opentracing/PendingTrace.java (hunk 5 above)
Comment (xgouchet) [reply features/dd-sdk-android-trace/src/main/java/com/datadog/opentracing/PendingTrace.java:183]: Good call.

File: features/dd-sdk-android-trace/src/main/java/com/datadog/opentracing/PendingTrace.java [hunk 6]
```diff
@@ -127,21 +127,23 @@ public void dropSpan(final DDSpan span) {
...
+      if (!traceId.equals(span.getTraceId())) {
+        return;
+      }
 
-    if (!isWritten.get()) {
-      addFirst(span);
-    } else {
+      if (!isWritten.get()) {
+        addFirst(span);
+      } else {
```
Comment (jonathanmos) [inline features/dd-sdk-android-trace/src/main/java/com/datadog/opentracing/PendingTrace.java:143]: what is the purpose of the empty else block?

File: features/dd-sdk-android-trace/src/test/kotlin/com/datadog/opentracing/PendingTraceTest.kt [hunk 7]
```diff
@@ -0,0 +1,122 @@
...
+
+        // When
+        val runnables = Array(CONCURRENT_THREAD) {
+            StressTestRunnable(pendingTrace, mockTracer, rootSpan, forge, countDownLatch)
+        }
+        runnables.forEach { Thread(it).start() }
+        countDownLatch.await(20, TimeUnit.SECONDS)
+
+        // Then
+        assertThat(countDownLatch.count).isZero()
```
Comment (jonathanmos) [inline features/dd-sdk-android-trace/src/test/kotlin/com/datadog/opentracing/PendingTraceTest.kt:55]: Is it necessary to assert that countdownlatch.count is zero if we're performed await? Shouldn't await block until the timeout or a count of zero?

Comment (jonathanmos) [inline features/dd-sdk-android-trace/src/test/kotlin/com/datadog/opentracing/PendingTraceTest.kt:55]: Do we need this assertion? Doesn't countdownlatch.await block until timeout or reaching a count of zero?

File: features/dd-sdk-android-trace/src/main/java/com/datadog/opentracing/PendingTrace.java [hunk 8]
```diff
@@ -127,21 +127,23 @@ public void dropSpan(final DDSpan span) {
...
-      return;
-    }
-    if (!traceId.equals(span.getTraceId())) {
-      return;
-    }
+    synchronized(this) {
+      if (span.getDurationNano() == 0) {
+        return;
+      }
+      if (traceId == null || span.context() == null) {
```
Comment (jonathanmos) [inline features/dd-sdk-android-trace/src/main/java/com/datadog/opentracing/PendingTrace.java:134]: I'm assuming that the reason all fail fast conditionals are separated is so that we can figure out exactly which one caused the problem in a stacktrace. If so, perhaps we should split this one also?

**Review by 0xnm — APPROVED** [review]
