### PR TITLE
RUMM-2780: Synchronize access to DatadogRumMonitor#rootScope when processing fatal error

### LINKED ISSUE #1178: Fatal Exception: java.util.ConcurrentModificationException
Thanks for taking the time for reporting an issue!

**Describe what happened**
Fatal Exception: java.util.ConcurrentModificationException
com.datadog.android.rum.internal.domain.scope.RumSessionScope.handleEvent (RumSessionScope.kt:88)
com.datadog.android.rum.internal.domain.scope.RumApplicationScope.handleEvent (RumApplicationScope.kt:51)
com.datadog.android.rum.internal.monitor.DatadogRumMonitor.handleEvent$dd_sdk_android_release (DatadogRumMonitor.kt:357)
com.datadog.android.rum.internal.monitor.DatadogRumMonitor.addCrash (DatadogRumMonitor.kt:272)

**Steps to reproduce the issue:**
RxJavaException will work and cause concurrency issues.

**Describe what you expected:**
I think we need to synchronize the reading and writing actions

**Additional context**
 - Android OS version: Android 12
 - Device Model: Galaxy S10 5G
 - Datadog SDK version: 1.13.0
 - Versions of any other relevant dependencies (OkHttp, …): 
 - Proguard configuration: 
 - Gradle Plugins: 1.5.1

### PR DESCRIPTION
**Pull request by 0xnm**
### What does this PR do?

Fixes #1178. When processing fatal error `rootScope` should be synchronized as well, as for the normal flow.

Otherwise 2 threads may enter `RumScope` simultaneously, leading to the different bugs like `ConcurrentModificationException`.

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

### CODE REVIEW

File: dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt [hunk 1]
```diff
@@ -1528,6 +1532,103 @@ internal class DatadogRumMonitorTest {
...
+                )
+                testedMonitor.handleEvent(event)
+            }
+        }
+
+        // Then
+        assertDoesNotThrow {
+            futures.forEach {
+                // none of these should throw
+                it.get()
```
Comment (mariusc83) [inline dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt:1627]: normally this should throw right if in the implementation above you are overriding the `get` method to throw an error.

Comment (mariusc83) [reply dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt:1627]: Oh it is not the same method, I think you should add some explanation here :) it is not at all obvious

**Review by mariusc83 — APPROVED** [review]

**Review by xgouchet — APPROVED** [review]
