### PR TITLE
RUMM-1180: Keep message for logs when it comes with error fields in OpenTracing format

### LINKED ISSUE #522: OpenTracing message field gets overridden by default "Span event" message in some cases
**Describe what happened**
In a log event that's attached to a span in a trace, when I set the OpenTracing message field `Fields.MESSAGE` and also set `Fields.EVENT` and `Fields.ERROR_KIND`, the `Fields.MESSAGE` value gets overridden with the default "Span event" message. When I only set `Fields.MESSAGE` and did not set `Fields.EVENT` and `Fields.ERROR_KIND`, the message was properly set.

**Steps to reproduce the issue:**

Message DOES NOT get set with the following:
```java
HashMap propertiesWithOpenTracingInfo = properties.toHashMap();
propertiesWithOpenTracingInfo.put(Fields.EVENT, "error");
propertiesWithOpenTracingInfo.put(Fields.ERROR_KIND, errorKind);
propertiesWithOpenTracingInfo.put(Fields.MESSAGE, message);
span.log(propertiesWithOpenTracingInfo);
```

Message IS correctly set with the following:
```java
HashMap propertiesWithOpenTracingInfo = properties.toHashMap();
propertiesWithOpenTracingInfo.put(Fields.MESSAGE, message);
span.log(propertiesWithOpenTracingInfo);
```

**Describe what you expected:**

On DataDog's website in Log Explorer, the message should be the message that I passed, i.e. `network request error`. But it is replaced with `Span event`, but only when I set other fields, i.e. in order to mark it as an error log.

**Additional context**
 - Android OS version: 11
 - Device Model: Samsung Galaxy S20
 - Datadog SDK version: 1.7.1
 - Versions of any other relevant dependencies (OkHttp, …): 
 - Proguard configuration: 
 - Gradle Plugins:

### PR DESCRIPTION
**Pull request by 0xnm**
### What does this PR do?

Fixes #522 . Before this change `MESSAGE` field was removed from the collection if it also contains error fields as part of `extractError` method, and then for the logs default message was used (since original was removed). But it actually makes sense to propagate it to the logs as well.

### Review checklist (to be filled by reviewers)

- [x] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [x] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [x] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

### CODE REVIEW

**Review by xgouchet — APPROVED** [review]

File: dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/handlers/AndroidSpanLogsHandler.kt [hunk 1]
```diff
@@ -85,7 +85,7 @@ internal class AndroidSpanLogsHandler(
 
         if (errorType != null) {
             val stackField = map.remove(Fields.STACK)
-            val msgField = map.remove(Fields.MESSAGE)
+            val msgField = map[Fields.MESSAGE]
```
Comment (mariusc83) [inline dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/handlers/AndroidSpanLogsHandler.kt:88]: I think the reason it was like that is that I followed what they are doing in the APM project.

**Review by mariusc83 — APPROVED** [review]
