### PR TITLE
RUM-3311 prevent crash when window is not hardware accelerated

### LINKED ISSUE #1875: IllegalArgumentException when removing OnFrameMetricsAvailableListener
### Stack trace

```
Caused by java.lang.IllegalArgumentException: attempt to remove OnFrameMetricsAvailableListener that was never added
       at android.view.View.removeFrameMetricsListener(View.java:7948)
       at android.view.Window.removeOnFrameMetricsAvailableListener(Window.java:997)
       at com.datadog.android.rum.internal.vitals.JankStatsActivityLifecycleListener.unregisterMetricListener(JankStatsActivityLifecycleListener.kt:216)
       at com.datadog.android.rum.internal.vitals.JankStatsActivityLifecycleListener.onActivityDestroyed(JankStatsActivityLifecycleListener.kt:163)
       at android.app.Application.dispatchActivityDestroyed(Application.java:576)
       at android.app.Activity.dispatchActivityDestroyed(Activity.java:1647)
       at android.app.Activity.onDestroy(Activity.java:2851)
       at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:257)
       at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:283)
       at com.company.features.onboarding.signup.main.ui.activity.Hilt_OnboardingSignupActivity.onDestroy(Hilt_OnboardingSignupActivity.java:64)
       at com.company.features.onboarding.signup.main.ui.activity.OnboardingSignupActivity.onDestroy(OnboardingSignupActivity.kt:77)
       at android.app.Activity.performDestroy(Activity.java:9236)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1491)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6135)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6180)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8893)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```
### Reproduction steps

_No response_

### Volume

Not yet significant

### Affected SDK versions

2.6.0

### Latest working SDK version

2.6.0

### Does the crash manifest in the latest SDK version?

Yes

### Kotlin / Java version

1.9.22

### Gradle / AGP version

8.6

### Other dependencies versions

_No response_

### Device Information

Brand:Samsung
Model:Galaxy S22+
Orientation:Portrait
RAM free: 3.23 GB
Disk free: 92.53 GB
Operating System
Version:Android 14
Orientation:Portrait
Rooted:No

### Other relevant information

_No response_

### PR DESCRIPTION
**Pull request by xgouchet**
### What does this PR do?

Prevent a crash when adding the JankStats listener

Fixes #1875

### CODE REVIEW

File: features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/vitals/JankStatsActivityLifecycleListener.kt [hunk 1]
```diff
@@ -200,20 +173,90 @@ internal class JankStatsActivityLifecycleListener(
...
+            // Fallback - Android 30 allows apps to not run at a fixed 60hz, but didn't yet have
+            // Frame Metrics callbacks available
+            val displayManager = activity.getSystemService(Context.DISPLAY_SERVICE) as DisplayManager
+            display = displayManager.getDisplay(Display.DEFAULT_DISPLAY)
+        }
+    }
+
+    @RequiresApi(Build.VERSION_CODES.S)
     private fun registerMetricListener(window: Window) {
         if (buildSdkVersionProvider.version() >= Build.VERSION_CODES.S) {
```
Comment (0xnm) [inline features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/vitals/JankStatsActivityLifecycleListener.kt:218]: optional: this check can be removed, we have it at the caller site and method is already annotated with `RequiresApi`

File: features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/vitals/JankStatsActivityLifecycleListener.kt [hunk 2]
```diff
@@ -200,20 +173,90 @@ internal class JankStatsActivityLifecycleListener(
...
+                )
+            }
         }
     }
 
     @RequiresApi(Build.VERSION_CODES.N)
     private fun unregisterMetricListener(window: Window) {
-        window.removeOnFrameMetricsAvailableListener(frameMetricsListener)
+        try {
+            window.removeOnFrameMetricsAvailableListener(frameMetricsListener)
```
Comment (0xnm) [inline features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/vitals/JankStatsActivityLifecycleListener.kt:251]: It is probably worth to check if `frameMetricsListener` is not null here before calling the method. Normally it cannot be at this point, since we got `onStart` call and created it, but just in case if it breaks in the future due to some refactoring.

In theory it is worth to check here for the hardware-accelerated view as well, but only if we are sure that `peekDecorView` at this point cannot be null (otherwise we may fail to remove listener).

**Review by 0xnm — APPROVED** [review]
nice, lgtm! I've added a few thoughts, but they are not blocking.

**Review by jonathanmos — APPROVED** [review]

**Review by 0xnm — APPROVED** [review]
